[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
# via_ir = true # Uncomment to use via IR

[profile.solx]
solc_version = "../../solx-binaries/solx-macosx-v0.1.0-alpha.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
